variable "create_sagemaker_domain" {
  type        = bool
  default     = true
  description = "Create Sagemaker domain or not"
}

variable "auth_mode" {
  type        = string
  default     = "IAM"
  description = "Authentication mode: IAM or SSO"
}

variable "domain_name" {
  type        = string
  default     = null
  description = "Domain name"
}

variable "subnet_ids" {
  type        = list(any)
  default     = []
  description = "List of subnets"
}

variable "tags" {
  type        = map(any)
  default     = {}
  description = "Tags"
}

variable "vpc_id" {
  type        = string
  default     = ""
  description = "VPC id"
}

variable "create_default_execution_role" {
  type        = bool
  default     = true
  description = "Create default execution role for the domain or not"
}

variable "default_execution_role_arn" {
  type        = string
  default     = ""
  description = "Default execution role ARN created outside the module"
}

variable "default_studio_web_portal" {
  type        = string
  default     = "ENABLED"
  description = "Enable Studio by default"
}

variable "default_execution_role_name" {
  type        = string
  default     = null
  description = "Default execution role name. Autogenerated if not provided"
}

variable "user_profiles" {
  type = map(object({
    role_arn  = optional(string, null)
    role_name = optional(string, null)
    policies  = optional(list(string), [])
  }))
  default     = {}
  description = "Map with user profiles and settings"
}

variable "user_profile_trusted_role_services" {
  type        = list(any)
  default     = ["sagemaker.amazonaws.com"]
  description = "List of trusted services"
}

